const { ActionRowBuilder, ButtonBuilder, ButtonStyle } = require("discord.js");
const { convertTime } = require("../../../functions/timeFormat.js");

const START_WH = "<:Start_WH:1550824319863492679>";
const START_BK = "<:Start_BK:1550824318223785984>";
const HALF_WH  = "<:Half_WH:1550824316633874482>";
const FULL_WH  = "<:Full_WH:1550824314423484416>";
const FULL_BK  = "<:Full_BK:1550824311751704638>";
const END_WH   = "<:End_WH:1550824309579055105>";
const END_BK   = "<:End_BK:1550824299873435658>";

const ICON_PREV    = "<:btn_prev:1550839283911368757>";
const ICON_PLAY    = "<:btn_play:1550839282418196560>";
const ICON_PAUSE   = "<:btn_pause:1550839287765803092>";
const ICON_SKIP    = "<:btn_skip:1550839286042067066>";
const ICON_VOLDOWN = "<:btn_voldown:1550839276613271633>";
const ICON_VOLUP   = "<:btn_volup:1550839279649947658>";
const ICON_STOP    = "<:btn_stop:1550839275346731078>";

const ICON_SPOTIFY = "<:spotify:1550848197981765723>"; // Replace ID
const ICON_YOUTUBE = "<:youtube:1550843332643655700>"; // Replace ID
const ICON_SOUNDCLOUD = "<:soundcloud:1550843334287953940>"; // Replace ID

function buildV2Payload(player, track, position = 0, forcePauseState = null) {
    const formatString = (str, maxLength) => (str.length > maxLength ? str.substr(0, maxLength - 3) + "..." : str);
    const safeTitle = (track.title || "Unknown").replace(/\[/g, "(").replace(/\]/g, ")");
    const trackTitle = formatString(safeTitle, 40).replace(/ - Topic$/, "");
    const trackAuthor = formatString(track.author || "Unknown", 30).replace(/ - Topic$/, "");
    
    const duration = track.duration || 0;
    const trackDuration = track.isStream ? "LIVE" : convertTime(duration);
    
    let bar = "";
    if (track.isStream) {
        bar = "🔴 LIVE";
    } else {
        const clampedPos = Math.min(position, duration);
        const percent = duration > 0 ? clampedPos / duration : 0;
        
        const totalMiddle = 13; 
        const filledMiddle = Math.round(percent * totalMiddle);
        
        let progressBar = "";
        progressBar += (percent > 0) ? START_WH : START_BK;

        for (let i = 0; i < totalMiddle; i++) {
            if (i < filledMiddle) {
                progressBar += FULL_WH;
            } else if (i === filledMiddle && percent > 0 && percent < 1) {
                progressBar += HALF_WH;
            } else {
                progressBar += FULL_BK;
            }
        }

        progressBar += (percent === 1) ? END_WH : END_BK;
        
        const current = convertTime(clampedPos);
        bar = `${current} ${progressBar} ${trackDuration}`;
    }

    let albumName = track.pluginInfo?.albumName || track.albumName || ""; 
    if (!albumName && track.aiMood) {
        albumName = track.aiMood; // Uses the AI text generated by trackStart.js
    }
    
    const requesterText = albumName ? `-# ${track.requester} • ${albumName}` : `-# ${track.requester}`;
    const volume = player.baseVolume ?? 100;

    let sourceIcon = ""; 
    if (track.source === "spotify") sourceIcon = ICON_SPOTIFY;
    else if (track.source === "youtube") sourceIcon = ICON_YOUTUBE;
    else if (track.source === "soundcloud") sourceIcon = ICON_SOUNDCLOUD;

    const textBlocks = [
        { type: 10, content: `[${trackTitle}](<${track.uri}>) — ${trackAuthor}  ${sourceIcon}\n${requesterText}` },
        { type: 10, content: `\n\u200b\n${bar}\n-# Volume ${volume}%` }
    ];

    const container = {
        type: 17, 
        components: track.artworkUrl
            ? [
                  {
                      type: 9, 
                      components: textBlocks,
                      accessory: {
                          type: 11, 
                          media: { url: track.artworkUrl }
                      }
                  }
              ]
            : textBlocks
    };

    const isPaused = forcePauseState !== null ? forcePauseState : player.paused;

    const row1 = new ActionRowBuilder().addComponents(
        new ButtonBuilder()
            .setCustomId("pause")
            .setEmoji(isPaused ? ICON_PLAY : ICON_PAUSE)
            .setStyle(ButtonStyle.Secondary),
        new ButtonBuilder().setCustomId("stop").setEmoji(ICON_STOP).setStyle(ButtonStyle.Secondary),
        new ButtonBuilder().setCustomId("skip").setEmoji(ICON_SKIP).setStyle(ButtonStyle.Secondary),
        new ButtonBuilder().setCustomId("voldown").setEmoji(ICON_VOLDOWN).setStyle(ButtonStyle.Secondary),
        new ButtonBuilder().setCustomId("volup").setEmoji(ICON_VOLUP).setStyle(ButtonStyle.Secondary)
    ).toJSON();

    return {
        flags: 32768, 
        components: [container, row1],
        allowedMentions: { parse: [] } 
    };
}

module.exports = async (client, player, data) => {
    if (!player || !player.message || !player.playing || player.paused) return;

    const track = player.queue.current;
    if (!track || track.isStream) return;

    const position = data?.state?.position ?? data?.position ?? player.position ?? 0;
    const duration = track.duration;
    if (!duration || duration <= 0) return;

    try {
        await player.message.edit(buildV2Payload(player, track, position));
    } catch (e) {
        // Message was deleted or missing permissions — silently ignore
    }
};
