const { EmbedBuilder, MessageFlags } = require("discord.js");

const { convertTime } = require("../../../functions/timeFormat.js");

const { queueLoudnessAnalysis, getCacheKey, applyGainCorrection } = require("../../../utils/loudness.js");



/**

 * Detects Spotify auto-generated playlists (Daily Mix, Discover Weekly, Release Radar, genre radio, etc.)

 * by checking for the characteristic error message from LavaSrc.

 * These have playlist IDs starting with "37i9dQZF1D" and are confirmed structurally inaccessible

 * via LavaSrc regardless of token type (Partner API or account tokens).

 * @param {string} errorMessage - The error message from the search result

 * @returns {boolean} True if the error indicates a Spotify auto-generated playlist

 */

function isSpotifyAutoGeneratedPlaylistError(errorMessage) {

    if (!errorMessage) return false;

    // LavaSrc throws this exact error for auto-generated playlists

    return errorMessage.includes("no longer accessible via anonymous tokens") ||

           errorMessage.includes("Spotify generated playlists");

}



/**

 * Checks if a query URL is a Spotify auto-generated playlist.

 * These have playlist IDs starting with "37i9dQZF1D".

 * @param {string} query - The search query/URL

 * @returns {boolean} True if the query matches Spotify auto-generated playlist pattern

 */

function isSpotifyAutoGeneratedPlaylistUrl(query) {

    if (!query) return false;

    // Match Spotify playlist URLs with the auto-generated ID prefix

    // Format: https://open.spotify.com/playlist/37i9dQZF1D...

    // or: spotify:playlist:37i9dQZF1D...

    const spotifyPlaylistRegex = /spotify\.com\/playlist\/37i9dQZF1D|spotify:playlist:37i9dQZF1D/i;

    return spotifyPlaylistRegex.test(query);

}


module.exports = {

    name: "play",

    description: "Play a song",

    category: "music",

    options: [

        {

            name: "query",

            description: "Provide a song name or url",

            type: 3,

            required: true,

            autocomplete: true,

        },

    ],

    permissions: {

        bot: ["Speak", "Connect"],

        user: ["Speak", "Connect"],

    },

    settings: {

        voice: true,

        player: false,

        current: false,

    },

    devOnly: false,

    run: async (client, interaction, player) => {

        // 1. Instantly acknowledge to prevent "Unknown interaction" timeout

        await interaction.deferReply();



        const embed = new EmbedBuilder().setColor(client.config.embedColor);



        // 2. Check if user is in the same voice channel

        if (player && player.voiceId !== interaction.member.voice.channelId) {

            embed.setDescription(`You must be in the same voice channel as the bot.`);

            return interaction.editReply({ embeds: [embed] });

        }



        const query = interaction.options.getString("query");

        

        // 3. Update the deferred message so the user knows the bot is searching

        await interaction.editReply({ embeds: [embed.setDescription(`Searching for \`${query}\``)] });

        

        // 4. Perform the search

        // Only specify sourceID for search queries (non-URLs), let Rainlink auto-detect for URLs

        const searchOptions = { requester: interaction.member };

        if (!query.startsWith('http')) {

            // Use the default search engine for non-URL queries

            searchOptions.sourceID = client.config.defaultSearchEngine === 'youtubeMusic' ? 'ym' :

                                 client.config.defaultSearchEngine === 'youtube' ? 'yt' :

                                 client.config.defaultSearchEngine === 'soundcloud' ? 'sc' :

                                 client.config.defaultSearchEngine === 'spotify' ? 'sp' :

                                 'yt'; // fallback to youtube

        } else {

            // For URLs, explicitly set sourceID based on URL platform to ensure proper handling

            // Use youtubeMusic source for all YouTube content to avoid ANDROID_VR login issues

            if (query.includes('youtube.com/watch') || query.includes('youtu.be/') ||

                query.includes('music.youtube.com') || query.includes('youtube.com/playlist')) {

                searchOptions.sourceID = 'ym'; // YouTube Music source (avoids login requirements)

            } else if (query.includes('spotify.com')) {

                // Spotify

                searchOptions.sourceID = 'sp';

            } else if (query.includes('soundcloud.com')) {

                // SoundCloud

                searchOptions.sourceID = 'sc';

            }

            // For other URLs, let Rainlink auto-detect (don't set sourceID)

        }

        // const result = await client.rainlink.search(query, searchOptions);
        let result = await client.rainlink.search(query, searchOptions);

        // Auto-retry once for Spotify URLs on transient Partner API failures
        // (Connection reset / 429 on first attempt is expected due to cold session;
        // 2nd attempt uses cached token and warm connection and reliably succeeds)
        if ((result.type === "ERROR" || !result.tracks?.length) && query.includes("spotify.com")) {
            await new Promise(r => setTimeout(r, 1500));
            result = await client.rainlink.search(query, searchOptions);
        }


        // 5. Handle empty or errored results

        if (result.type === "EMPTY" || result.type === "ERROR" || !result.tracks.length) {

            // Extract error message from various possible locations in the result object

            const errorMessage = result.exception?.message

                || result.exception?.cause?.message

                || (result.exception?.cause && typeof result.exception.cause === 'object' && result.exception.cause.message)

                || (Array.isArray(result.exception?.errors) && result.exception.errors.map(e => e.message).join(' '))

                || "";



            // Log detailed error information for debugging

            if (result.type === "ERROR" && errorMessage) {

                console.error(`[PLAY COMMAND] Search error for query "${query}":`, errorMessage);

                console.error(`[PLAY COMMAND] Full result object:`, JSON.stringify(result, null, 2));

            }



            // Check if this is a Spotify auto-generated playlist error (from exception)

            if (isSpotifyAutoGeneratedPlaylistError(errorMessage)) {

                embed.setDescription(

                    `⚠️ **Spotify auto-generated playlists (Daily Mix, Discover Weekly, Release Radar, radio stations, etc.) sometimes fail to load due to a Spotify-side restriction.**\n\n` +

                    `The playlist you tried to play couldn't be loaded this time. You can try again — it may work on another attempt — or copy the songs into your own playlist on Spotify first for reliable playback.`

                );

                return interaction.editReply({ embeds: [embed] });

            }



            // Check if this is a Spotify auto-generated playlist URL (even if no exception captured)

            // This handles the case where Rainlink returns empty result without preserving the exception

            if (isSpotifyAutoGeneratedPlaylistUrl(query)) {

                embed.setDescription(

                    `⚠️ **Spotify auto-generated playlists (Daily Mix, Discover Weekly, Release Radar, radio stations, etc.) sometimes fail to load due to a Spotify-side restriction.**\n\n` +

                    `The playlist you tried to play couldn't be loaded this time. You can try again — it may work on another attempt — or copy the songs into your own playlist on Spotify first for reliable playback.`

                );

                return interaction.editReply({ embeds: [embed] });

            }



            // Provide more specific error messages based on result type

            if (result.type === "ERROR") {

                embed.setDescription(`Search error: ${errorMessage || 'Unknown error occurred during search.'}`);

            } else if (result.type === "EMPTY") {

                embed.setDescription(`No results found for your query. The video may be unavailable, restricted, or the search returned no results.`);

            } else if (!result.tracks.length) {

                embed.setDescription(`Search completed but no tracks were found. Please TRY AGAIN`);

            } else {

                embed.setDescription(`No results found for your query.`);

            }

            return interaction.editReply({ embeds: [embed] });

        }



        // 6. Create the player if one doesn't exist yet

        if (!player) {

            player = await client.rainlink.create({

                guildId: interaction.guildId,

                textId: interaction.channelId,

                voiceId: interaction.member.voice.channelId,

                shardId: interaction.guild.shardId,

                volume: client.config.defaultVolume,

                deaf: true,

            });

            // Initialize played history for autoplay no-repeat (Task 7)

            player.playedHistory = new Set();

        }



        // 7. Process the search results into the queue

        if (result.type === "PLAYLIST") {

            // Check if adding the playlist would exceed queue limit

            const currentSize = player.queue.size + (player.playing ? 1 : 0);

            const availableSpace = client.config.maxQueueSize - currentSize;

            

            if (availableSpace <= 0) {

                embed.setDescription(`Queue is full (max ${client.config.maxQueueSize} tracks). Cannot add playlist.`);

                return interaction.editReply({ embeds: [embed] });

            }

            

            let tracksAdded = 0;

            for (const track of result.tracks) {

                // Stop adding if we would exceed the limit

                if (currentSize + tracksAdded >= client.config.maxQueueSize) {

                    break;

                }

                player.queue.add(track);

                // Kick off background loudness analysis (fire-and-forget)

                // Pass callback to apply gain if this track is currently playing

                queueLoudnessAnalysis(track, (cached, avgGain) => {

                    if (player.queue.current && getCacheKey(player.queue.current) === getCacheKey(track)) {

                        applyGainCorrection(player, player.queue.current, client);

                    }

                });

                tracksAdded++;

            }



            if (tracksAdded === 0) {

                embed.setDescription(`Queue is full (max ${client.config.maxQueueSize} tracks). Cannot add any tracks from this playlist.`);

                return interaction.editReply({ embeds: [embed] });

            } else if (tracksAdded < result.tracks.length) {

                embed.setDescription(`Added **${tracksAdded}** of **${result.tracks.length}** songs from **[${result.playlistName}](${query})**. Queue limit reached.`);

            } else {

                embed.setDescription(`Added **[${result.playlistName}](${query})** - \`${result.tracks.length}\` songs to the queue.`);

            }

        } else {

            // Single track

            const currentSize = player.queue.size + (player.playing ? 1 : 0);

            

            if (currentSize >= client.config.maxQueueSize) {

                embed.setDescription(`Queue is full (max ${client.config.maxQueueSize} tracks). Cannot add this track.`);

                return interaction.editReply({ embeds: [embed] });

            }



            const track = result.tracks[0];

            const trackTitle = formatString(track.title, 30).replace(/ - Topic$/, "") || "Unknown";

            const trackAuthor = formatString(track.author, 25).replace(/ - Topic$/, "") || "Unknown";



            player.queue.add(track);

            // Kick off background loudness analysis (fire-and-forget)

            // Pass callback to apply gain if this track is currently playing

            queueLoudnessAnalysis(track, (cached, avgGain) => {

                if (player.queue.current && getCacheKey(player.queue.current) === getCacheKey(track)) {

                    applyGainCorrection(player, player.queue.current, client);

                }

            });



            embed.setDescription(`Added **[${trackTitle} - ${trackAuthor}](${track.uri})** - \`${convertTime(track.duration)}\`.`);

        }



        // 8. Show the final success message (replaced the old msg.edit)

        await interaction.editReply({ embeds: [embed] });

        

        // 9. Start the music!

        if (!player.playing) return player.play();

    },

};



function formatString(str, maxLength) {

    return str.length > maxLength ? str.substr(0, maxLength - 3) + "..." : str;

}



// Simple in-memory cache for recent autocomplete queries to reduce latency

// Cache search results for 60 seconds
const __autocompleteCache = new Map(); // key -> { ts, choices }

// Track the latest keystroke per user for debouncing
const __userTypingTracker = new Map(); // userId -> latestFocusedString

// Sleep helper
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// Helper: promise with timeout
function withTimeout(promise, ms) {
    return Promise.race([
        promise,
        new Promise((resolve) => setTimeout(() => resolve(null), ms)),
    ]);
}

// --- SPOTIFY TOKEN MEMORY CACHE ---
let cachedSpotifyToken = null;
let tokenExpiresAt = 0;
let isFetchingToken = false; // Prevents spamming the API with requests

// Background Task: Fetch a new token if expired
async function refreshSpotifyTokenBackground() {
    if (isFetchingToken) return;
    isFetchingToken = true;
    try {
        console.log(`[Spotify] Token missing/expired. Fetching new one in background...`);
        const res = await fetch("http://127.0.0.1:3000/api/token");
        if (res.ok) {
            const data = await res.json();
            if (data.access_token) {
                cachedSpotifyToken = data.access_token;
                // Safely cache for 50 minutes (3000000 ms) to leave a buffer before true expiration
                tokenExpiresAt = Date.now() + (50 * 60 * 1000); 
                console.log(`[Spotify] Background fetch complete. New token active.`);
            }
        }
    } catch (e) {
        console.log(`[Spotify] Background token fetch failed:`, e.message);
    } finally {
        isFetchingToken = false;
    }
}

// Background Task: Rotate burner account if Spotify API rate-limits us
async function rotateSpotifyTokenBackground() {
    if (isFetchingToken) return;
    isFetchingToken = true;
    try {
        console.log(`[Spotify] 429 Rate Limit Hit! Triggering burner account rotation in background...`);
        const res = await fetch("http://127.0.0.1:3000/api/rotate/token");
        if (res.ok) {
            const data = await res.json();
            if (data.access_token) {
                cachedSpotifyToken = data.access_token;
                tokenExpiresAt = Date.now() + (50 * 60 * 1000);
                console.log(`[Spotify] Rotation successful. Swapped to [${data.account}].`);
            }
        }
    } catch (e) {
        console.log(`[Spotify] Background rotation failed:`, e.message);
    } finally {
        isFetchingToken = false;
    }
}

// Search Spotify Web API directly with non-blocking failovers
async function searchSpotifyDirect(query, limit = 5) {
    // 1. FAST-FAIL: If token is missing or expired, return empty instantly and fetch in background
    if (!cachedSpotifyToken || Date.now() > tokenExpiresAt) {
        refreshSpotifyTokenBackground(); // Fire and forget
        return [];
    }

    try {
        // Fetch 10 results so we have a larger pool to filter down
        const url = `https://api.spotify.com/v1/search?q=${encodeURIComponent(query)}&type=track&market=TH&limit=10`;
        const res = await fetch(url, {
            headers: { Authorization: `Bearer ${cachedSpotifyToken}` },
        });

        // 2. ERROR HANDLING: Check for Spotify API limits or dead tokens
        if (!res.ok) {
            if (res.status === 429) {
                // Rate limited by Spotify! Wipe memory and rotate burner account.
                cachedSpotifyToken = null;
                rotateSpotifyTokenBackground(); // Fire and forget
            } else if (res.status === 401) {
                // Token is randomly invalid. Wipe and fetch a new one.
                cachedSpotifyToken = null;
                refreshSpotifyTokenBackground(); // Fire and forget
            }
            return []; // Return empty instantly so Discord doesn't timeout
        }

        const data = await res.json();
        const tracks = data.tracks?.items || [];

        const uniqueTracks = [];
        const seenKeys = new Set();
        const lowerQuery = query.toLowerCase();

        for (const track of tracks) {
            const title = track.name || "Unknown";
            const artist = track.artists?.[0]?.name || "Unknown";
            
            // Strict Matching
            const isMatch = title.toLowerCase().includes(lowerQuery) || artist.toLowerCase().includes(lowerQuery);
            if (!isMatch) continue;

            // Deduplication
            const dedupKey = `${title.toLowerCase()} - ${artist.toLowerCase()}`;
            if (seenKeys.has(dedupKey)) continue;
            seenKeys.add(dedupKey);

            let label = `🟢 ${title} — ${artist}`;
            if (label.length > 100) label = label.substring(0, 97) + "...";

            const value = track.external_urls?.spotify || `${title} - ${artist}`;
            
            uniqueTracks.push({
                name: label,
                value: value.length > 100 ? value.substring(0, 100) : value,
            });

            if (uniqueTracks.length >= limit) break;
        }

        return uniqueTracks;
    } catch (e) {
        return [];
    }
}

// Autocomplete handler for `/play`
module.exports.autocomplete = async (client, interaction) => {
    const handlerStart = Date.now();
    try {
        const focused = interaction.options.getFocused();
        const trimmed = focused ? focused.trim() : "";

        // 1. Minimum character barrier: ignore 0 or 1 character queries
        if (trimmed.length < 2) {
            return interaction.respond([]);
        }

        // 2. Return cached results immediately if searched recently (60-second TTL)
        const cacheKey = `play:autocomplete:${trimmed.toLowerCase()}`;
        const cached = __autocompleteCache.get(cacheKey);
        const now = Date.now();
        if (cached && now - cached.ts < 60000) {
            return interaction.respond(cached.choices.slice(0, 15));
        }

        // 3. Debounce: Register current query and wait 200ms
        const userId = interaction.user.id;
        __userTypingTracker.set(userId, focused);

        await sleep(200);

        // If the user typed another character during the 200ms window, drop this request
        if (__userTypingTracker.get(userId) !== focused) {
            return interaction.respond([]); 
        }

        const perSource = 5;
        const perSourceTimeout = 2200; // Leave buffer under Discord's 3-second limit

        // 4. Run Spotify & YouTube in parallel only when the user pauses typing
        const [spotifyChoices, ytChoices] = await Promise.all([
            withTimeout(searchSpotifyDirect(trimmed, perSource), perSourceTimeout).then((r) => r || []),
            withTimeout(
                client.rainlink.search(trimmed, { requester: interaction.user, sourceID: "yt" }).catch(() => null),
                perSourceTimeout
            ).then((res) => {
                if (!res?.tracks || !Array.isArray(res.tracks)) return [];
                return res.tracks.slice(0, perSource).map((t) => {
                    const title = (t.title || t.info?.title || "Unknown").toString();
                    const author = (t.author || t.info?.author || "Unknown").toString();
                    let label = `🔴 ${title} — ${author}`;
                    if (label.length > 100) label = label.substring(0, 97) + "...";
                    return {
                        name: label,
                        value: (t.uri || t.info?.uri || `${title} - ${author}`).toString(),
                    };
                });
            }).catch(() => []),
        ]);

        const finalChoices = [...spotifyChoices, ...ytChoices].slice(0, 25);
        const totalElapsed = Date.now() - handlerStart;

        try {
            client.utils?.logger?.debug?.(
                `[Autocomplete] responding with ${finalChoices.length} choices in ${totalElapsed}ms for query="${focused}"`
            );
        } catch (e) {}

        // Save choices into cache
        __autocompleteCache.set(cacheKey, { ts: now, choices: finalChoices });

        // Clean up the user's debounce state
        if (__userTypingTracker.get(userId) === focused) {
            __userTypingTracker.delete(userId);
        }

        return interaction.respond(finalChoices);
    } catch (error) {
        try {
            client.utils?.logger?.error?.("Autocomplete error:", error);
        } catch (e) {}
        
        try {
            return interaction.respond([]);
        } catch (e) {}
    }
};


/**

 * Project: Lunox

 * Author: adh319

 * Company: EnourDev

 * This code is the property of EnourDev and may not be reproduced or

 * modified without permission. For more information, contact us at

 * https://discord.gg/xhTVzbS5NU

 */ 

