const { EmbedBuilder, MessageFlags } = require("discord.js");
const { convertTime } = require("../../../functions/timeFormat.js");
const { queueLoudnessAnalysis, getCacheKey, applyGainCorrection } = require("../../../utils/loudness.js");

const { fetch } = require('undici');
const spotify = require('spotify-url-info')(fetch);

/**
 * Detects Spotify auto-generated playlists (Daily Mix, Discover Weekly, Release Radar, genre radio, etc.)
 * by checking for the characteristic error message from LavaSrc.
 * These have playlist IDs starting with "37i9dQZF1D" and are confirmed structurally inaccessible
 * via LavaSrc regardless of token type (Partner API or account tokens).
 * @param {string} errorMessage - The error message from the search result
 * @returns {boolean} True if the error indicates a Spotify auto-generated playlist
 */
function isSpotifyAutoGeneratedPlaylistError(errorMessage) {
    if (!errorMessage) return false;
    // LavaSrc throws this exact error for auto-generated playlists
    return errorMessage.includes("no longer accessible via anonymous tokens") ||
           errorMessage.includes("Spotify generated playlists");
}

/**
 * Checks if a query URL is a Spotify auto-generated playlist.
 * These have playlist IDs starting with "37i9dQZF1D".
 * @param {string} query - The search query/URL
 * @returns {boolean} True if the query matches Spotify auto-generated playlist pattern
 */
function isSpotifyAutoGeneratedPlaylistUrl(query) {
    if (!query) return false;
    // Match Spotify playlist URLs with the auto-generated ID prefix
    // Format: https://open.spotify.com/playlist/37i9dQZF1D...
    // or: spotify:playlist:37i9dQZF1D...
    const spotifyPlaylistRegex = /spotify\.com\/playlist\/37i9dQZF1D|spotify:playlist:37i9dQZF1D/i;
    return spotifyPlaylistRegex.test(query);
}

module.exports = {
    name: "play",
    description: "Play a song",
    category: "music",
    options: [
        {
            name: "query",
            description: "Provide a song name or url",
            type: 3,
            required: true,
            autocomplete: true,
        },
    ],
    permissions: {
        bot: ["Speak", "Connect"],
        user: ["Speak", "Connect"],
    },
    settings: {
        voice: true,
        player: false,
        current: false,
    },
    devOnly: false,
    run: async (client, interaction, player) => {
        // 1. Instantly acknowledge to prevent "Unknown interaction" timeout
        await interaction.deferReply();

        const embed = new EmbedBuilder().setColor(client.config.embedColor);

        // 2. Check if user is in the same voice channel
        if (player && player.voiceId !== interaction.member.voice.channelId) {
            embed.setDescription(`You must be in the same voice channel as the bot.`);
            return interaction.editReply({ embeds: [embed] });
        }

        let query = interaction.options.getString("query");

// 3. Update the deferred message so the user knows the bot is searching
        await interaction.editReply({ embeds: [embed.setDescription(`Searching for \`${query}\``)] });
        
        // --- SPOTIFY BYPASS START ---
        let isSpotifyScraped = false;
        let scrapedTracks = [];

        if (query.match(/open\.spotify\.com\/(track|album|playlist)/)) {
            try {
                const spotifyData = await spotify.getTracks(query);
                if (spotifyData && spotifyData.length > 0) {
                    isSpotifyScraped = true;
                    scrapedTracks = spotifyData;
                    
                    // Overwrite the query with the first track to get playback started instantly
                    query = `${scrapedTracks[0].name} ${scrapedTracks[0].artists?.[0]?.name || ''}`.trim();
                    
                    // Update the bot's message so the user sees it successfully grabbed the track
                    await interaction.editReply({ embeds: [embed.setDescription(`Scraped Spotify! Searching for \`${query}\``)] });
                }
            } catch (e) {
                console.error("[Spotify Bypass] Scrape failed:", e);
            }
        }

        // 4. Perform the search
        const searchOptions = { requester: interaction.member };
        
        if (isSpotifyScraped) {
            // searchOptions.sourceID = 'ym'; // Force YouTube Music for scraped Spotify tracks
        } else if (!query.startsWith('http')) {
            // Use the default search engine for non-URL queries
            searchOptions.sourceID = client.config.defaultSearchEngine === 'youtube' ? 'yt' :
                                     client.config.defaultSearchEngine === 'youtubeMusic' ? 'yt' :
                                     client.config.defaultSearchEngine === 'soundcloud' ? 'sc' :
                                     client.config.defaultSearchEngine === 'spotify' ? 'sp' :
                                     'yt'; // fallback to youtube
        } else {
            // For URLs, explicitly set sourceID based on URL platform to ensure proper handling
            if (query.includes('youtube.com/watch') || query.includes('youtu.be/') ||
                query.includes('music.youtube.com') || query.includes('youtube.com/playlist')) {
                searchOptions.sourceID = 'yt'; 
            } else if (query.includes('spotify.com')) {
                searchOptions.sourceID = 'sp';
            } else if (query.includes('soundcloud.com')) {
                searchOptions.sourceID = 'sc';
            }
        }
        
        const result = await client.rainlink.search(query, searchOptions);
        // --- SPOTIFY BYPASS END ---

        // 5. Handle empty or errored results
        if (result.type === "EMPTY" || result.type === "ERROR" || !result.tracks.length) {
            // Extract error message from various possible locations in the result object
            const errorMessage = result.exception?.message
                || result.exception?.cause?.message
                || (result.exception?.cause && typeof result.exception.cause === 'object' && result.exception.cause.message)
                || (Array.isArray(result.exception?.errors) && result.exception.errors.map(e => e.message).join(' '))
                || "";

            // Log detailed error information for debugging
            if (result.type === "ERROR" && errorMessage) {
                console.error(`[PLAY COMMAND] Search error for query "${query}":`, errorMessage);
                console.error(`[PLAY COMMAND] Full result object:`, JSON.stringify(result, null, 2));
            }

            // Check if this is a Spotify auto-generated playlist error (from exception)
            if (isSpotifyAutoGeneratedPlaylistError(errorMessage)) {
                embed.setDescription(
                    `⚠️ **Spotify auto-generated playlists (Daily Mix, Discover Weekly, Release Radar, radio stations, etc.) sometimes fail to load due to a Spotify-side restriction.**\n\n` +
                    `The playlist you tried to play couldn't be loaded this time. You can try again — it may work on another attempt — or copy the songs into your own playlist on Spotify first for reliable playback.`
                );
                return interaction.editReply({ embeds: [embed] });
            }

            // Check if this is a Spotify auto-generated playlist URL (even if no exception captured)
            // This handles the case where Rainlink returns empty result without preserving the exception
            if (isSpotifyAutoGeneratedPlaylistUrl(query)) {
                embed.setDescription(
                    `⚠️ **Spotify auto-generated playlists (Daily Mix, Discover Weekly, Release Radar, radio stations, etc.) sometimes fail to load due to a Spotify-side restriction.**\n\n` +
                    `The playlist you tried to play couldn't be loaded this time. You can try again — it may work on another attempt — or copy the songs into your own playlist on Spotify first for reliable playback.`
                );
                return interaction.editReply({ embeds: [embed] });
            }

            // Provide more specific error messages based on result type
            if (result.type === "ERROR") {
                embed.setDescription(`Search error: ${errorMessage || 'Unknown error occurred during search.'}`);
            } else if (result.type === "EMPTY") {
                embed.setDescription(`No results found for your query. The video may be unavailable, restricted, or the search returned no results.`);
            } else if (!result.tracks.length) {
                embed.setDescription(`Search completed but no tracks were found.`);
            } else {
                embed.setDescription(`No results found for your query.`);
            }
            return interaction.editReply({ embeds: [embed] });
        }

        // 6. Create the player if one doesn't exist yet
        if (!player) {
            player = await client.rainlink.create({
                guildId: interaction.guildId,
                textId: interaction.channelId,
                voiceId: interaction.member.voice.channelId,
                shardId: interaction.guild.shardId,
                volume: client.config.defaultVolume,
                deaf: true,
            });
            // Initialize played history for autoplay no-repeat (Task 7)
            player.playedHistory = new Set();
        }

        // 7. Process the search results into the queue
        if (result.type === "PLAYLIST") {
            // Check if adding the playlist would exceed queue limit
            const currentSize = player.queue.size + (player.playing ? 1 : 0);
            const availableSpace = client.config.maxQueueSize - currentSize;
            
            if (availableSpace <= 0) {
                embed.setDescription(`Queue is full (max ${client.config.maxQueueSize} tracks). Cannot add playlist.`);
                return interaction.editReply({ embeds: [embed] });
            }
            
            let tracksAdded = 0;
            for (const track of result.tracks) {
                // Stop adding if we would exceed the limit
                if (currentSize + tracksAdded >= client.config.maxQueueSize) {
                    break;
                }
                player.queue.add(track);
                // Kick off background loudness analysis (fire-and-forget)
                // Pass callback to apply gain if this track is currently playing
                queueLoudnessAnalysis(track, (cached, avgGain) => {
                    if (player.queue.current && getCacheKey(player.queue.current) === getCacheKey(track)) {
                        applyGainCorrection(player, player.queue.current, client);
                    }
                });
                tracksAdded++;
            }

            if (tracksAdded === 0) {
                embed.setDescription(`Queue is full (max ${client.config.maxQueueSize} tracks). Cannot add any tracks from this playlist.`);
                return interaction.editReply({ embeds: [embed] });
            } else if (tracksAdded < result.tracks.length) {
                embed.setDescription(`Added **${tracksAdded}** of **${result.tracks.length}** songs from **[${result.playlistName}](${query})**. Queue limit reached.`);
            } else {
                embed.setDescription(`Added **[${result.playlistName}](${query})** - \`${result.tracks.length}\` songs to the queue.`);
            }
        } else {
            // Single track
            const currentSize = player.queue.size + (player.playing ? 1 : 0);
            
            if (currentSize >= client.config.maxQueueSize) {
                embed.setDescription(`Queue is full (max ${client.config.maxQueueSize} tracks). Cannot add this track.`);
                return interaction.editReply({ embeds: [embed] });
            }

            const track = result.tracks[0];
            const trackTitle = formatString(track.title, 30).replace(/ - Topic$/, "") || "Unknown";
            const trackAuthor = formatString(track.author, 25).replace(/ - Topic$/, "") || "Unknown";

            player.queue.add(track);
            // Kick off background loudness analysis (fire-and-forget)
            // Pass callback to apply gain if this track is currently playing
            queueLoudnessAnalysis(track, (cached, avgGain) => {
                if (player.queue.current && getCacheKey(player.queue.current) === getCacheKey(track)) {
                    applyGainCorrection(player, player.queue.current, client);
                }
            });

            embed.setDescription(`Added **[${trackTitle} - ${trackAuthor}](${track.uri})** - \`${convertTime(track.duration)}\`.`);
        }

        // 8. Show the final success message (replaced the old msg.edit)
        await interaction.editReply({ embeds: [embed] });
        
        // 9. Start the music!
        if (!player.playing) player.play();

        // --- SPOTIFY BACKGROUND QUEUE START ---
        if (isSpotifyScraped && scrapedTracks.length > 1) {
            const bgEmbed = new EmbedBuilder()
                .setColor(client.config.embedColor)
                .setDescription(`🎵 Scraped **${scrapedTracks.length}** tracks from Spotify. Loading the rest in the background...`);
            await interaction.channel.send({ embeds: [bgEmbed] });

            // Run in background so it doesn't freeze the bot
            (async () => {
                let tracksAdded = 1; // First track is already added
                
                for (let i = 1; i < scrapedTracks.length; i++) {
                    const currentSize = player.queue.size + (player.playing ? 1 : 0);
                    if (currentSize >= client.config.maxQueueSize) break; // Respect bot queue limits

                    const trackInfo = scrapedTracks[i];
                    const searchStr = `${trackInfo.name} ${trackInfo.artists?.[0]?.name || ''}`.trim();
                    
                    try {
                        const searchRes = await client.rainlink.search(searchStr, { requester: interaction.member, sourceID: 'yt' });
                        
                        if (searchRes.tracks && searchRes.tracks.length > 0) {
                            const newTrack = searchRes.tracks[0];
                            player.queue.add(newTrack);
                            
                            // Re-apply Lunox's loudness analysis for background tracks
                            queueLoudnessAnalysis(newTrack, (cached, avgGain) => {
                                if (player.queue.current && getCacheKey(player.queue.current) === getCacheKey(newTrack)) {
                                    applyGainCorrection(player, player.queue.current, client);
                                }
                            });
                            tracksAdded++;
                        }
                    } catch (e) {
                        // Skip if a single track fails to search
                    }
                    
                    // Add a small 400ms delay between searches so YouTube doesn't IP ban/rate-limit the bot
                    await new Promise(res => setTimeout(res, 1400));
                }
                
                const doneEmbed = new EmbedBuilder()
                    .setColor(client.config.embedColor)
                    .setDescription(`✅ Finished loading **${tracksAdded}** Spotify tracks!`);
                await interaction.channel.send({ embeds: [doneEmbed] });
            })();
        }
        // --- SPOTIFY BACKGROUND QUEUE END ---
    },
};

function formatString(str, maxLength) {
    return str.length > maxLength ? str.substr(0, maxLength - 3) + "..." : str;
}

// Simple in-memory cache for recent autocomplete queries to reduce latency
const __autocompleteCache = new Map(); // key -> { ts, choices }

// Helper: promise with timeout
function withTimeout(promise, ms) {
    return Promise.race([
        promise,
        new Promise((resolve) => setTimeout(() => resolve(null), ms)),
    ]);
}

// Autocomplete handler for `/play` — searches two sources in parallel with timeouts, cache, and timing logs
module.exports.autocomplete = async (client, interaction) => {
    const handlerStart = Date.now();
    try {
        const focused = interaction.options.getFocused();

        // --- PREVENT SPOTIFY URLS FROM SPAMMING LAVALINK ERRORS ---
        if (focused.match(/open\.spotify\.com/)) {
            return interaction.respond([{ 
                name: "🎵 Spotify Link Detected - Press Enter to load bypass!", 
                value: focused 
            }]);
        }
        // ----------------------------------------------------------
        
        if (!focused || focused.length === 0) {
            try {
                client.utils?.logger?.debug?.(`[Autocomplete] empty focused for /play`);
            } catch (e) {}
            return interaction.respond([]);
        }

        // Return cached results if recent (TTL 3000ms)
        const cacheKey = `play:autocomplete:${focused}`;
        const cached = __autocompleteCache.get(cacheKey);
        const now = Date.now();
        if (cached && now - cached.ts < 3000) {
            try {
                client.utils?.logger?.debug?.(`[Autocomplete] cache hit for query="${focused}" (${now - cached.ts}ms old)`);
            } catch (e) {}
            return interaction.respond(cached.choices.slice(0, 15));
        }

        const perSource = 5; // 5 results per source
        const sources = [
            { id: "sp", name: "Spotify", icon: "🟢" },
            { id: "yt", name: "YouTube", icon: "🔴" },
        ];

        // Per-source timeout in ms — keep this comfortably under Discord's interaction deadline
        const perSourceTimeout = 2500;

        // Fan-out with per-source timing
        const searchPromises = sources.map((s) => {
            const srcStart = Date.now();
            return withTimeout(
                client.rainlink.search(focused, { requester: interaction.user, sourceID: s.id }).catch(() => null),
                perSourceTimeout,
            ).then((res) => {
                const elapsed = Date.now() - srcStart;
                try {
                    if (!res || !res.tracks || !Array.isArray(res.tracks)) {
                        client.utils?.logger?.debug?.(`[Autocomplete] ${s.name} (${s.id}) settled in ${elapsed}ms — no data/timeout for query="${focused}"`);
                    } else {
                        client.utils?.logger?.debug?.(`[Autocomplete] ${s.name} (${s.id}) settled in ${elapsed}ms — ${res.tracks.length} hits for query="${focused}"`);
                    }
                } catch (e) {}

                return { source: s.name, id: s.id, icon: s.icon, data: res, elapsed };
            }).catch((err) => {
                const elapsed = Date.now() - srcStart;
                try { client.utils?.logger?.debug?.(`[Autocomplete] ${s.name} (${s.id}) rejected in ${elapsed}ms for query="${focused}": ${String(err)}`); } catch(e){}
                return { source: s.name, id: s.id, icon: s.icon, data: null, elapsed };
            });
        });

        // Await the parallel searches — with per-source timeouts these are independent
        const results = await Promise.all(searchPromises);

        const choices = [];

        for (const result of results) {
            if (!result || !result.data || !Array.isArray(result.data.tracks)) continue;
            const tracks = result.data.tracks.slice(0, perSource);

            for (const t of tracks) {
                const title = (t.title || t.info?.title || "Unknown").toString();
                const author = (t.author || t.info?.author || "Unknown").toString();
                // Prepend source icon so users know which source each result came from
                const srcIcon = result.icon ? `${result.icon} ` : "";
                let label = `${srcIcon}${title} — ${author}`;
                if (label.length > 100) label = label.substring(0, 97) + "...";

                const value = (t.uri || t.info?.uri || `${title} - ${author}`).toString();

                choices.push({ name: label, value });

                if (choices.length >= 25) break;
            }

            if (choices.length >= 25) break;
        }

        // Limit to per-source count * number of sources (e.g., 5 * 2 = 10)
        const finalChoices = choices.slice(0, perSource * sources.length);

        const totalElapsed = Date.now() - handlerStart;
        try {
            client.utils?.logger?.debug?.(`[Autocomplete] responding with ${finalChoices.length} choices in ${totalElapsed}ms for query="${focused}"`);
        } catch (e) {}

        // Cache the choices briefly to speed up rapid repeated keystrokes
        __autocompleteCache.set(cacheKey, { ts: now, choices: finalChoices });

        return interaction.respond(finalChoices);
    } catch (error) {
        // Logging but avoid throwing — reply empty to keep the client responsive
        try {
            client.utils?.logger?.error?.("Autocomplete error:", error);
        } catch (e) {}

        try {
            return interaction.respond([]);
        } catch (e) {}
    }
};

/**
 * Project: Lunox
 * Author: adh319
 * Company: EnourDev
 * This code is the property of EnourDev and may not be reproduced or
 * modified without permission. For more information, contact us at
 * https://discord.gg/xhTVzbS5NU
 */