const { MessageFlags } = require("discord.js");
const { convertTime } = require("../../../functions/timeFormat.js");
const { queueLoudnessAnalysis, getCacheKey, applyGainCorrection } = require("../../../utils/loudness.js");

const SPOTIFY_RETRY_COUNT = 4;    // number of retries after first failure
const SPOTIFY_RETRY_DELAY_MS = 2000; // ms to wait between each retry

// ==========================================
// 🎨 V2 COMPONENT MESSAGE BUILDER
// ==========================================
function buildV2Message(text) {
    return {
        flags: 32768, // IS_COMPONENTS_V2
        embeds: [],   // Clear any legacy embeds
        components: [
            {
                type: 17, // ComponentType.CONTAINER
                components: [
                    { type: 10, content: text } // ComponentType.TEXT_DISPLAY
                ]
            }
        ]
    };
}

function isSpotifyAutoGeneratedPlaylistError(errorMessage) {
    if (!errorMessage) return false;
    return errorMessage.includes("no longer accessible via anonymous tokens") ||
           errorMessage.includes("Spotify generated playlists");
}

function isSpotifyAutoGeneratedPlaylistUrl(query) {
    if (!query) return false;
    const spotifyPlaylistRegex = /spotify\.com\/playlist\/37i9dQZF1D|spotify:playlist:37i9dQZF1D/i;
    return spotifyPlaylistRegex.test(query);
}

module.exports = {
    name: "play",
    description: "Play a song",
    category: "music",
    options: [
        {
            name: "query",
            description: "Provide a song name or url",
            type: 3,
            required: true,
            autocomplete: true,
        },
    ],
    permissions: {
        bot: ["Speak", "Connect"],
        user: ["Speak", "Connect"],
    },
    settings: {
        voice: true,
        player: false,
        current: false,
    },
    devOnly: false,
    run: async (client, interaction, player) => {

        const e = client.config.emojis;

        // 1. Instantly acknowledge
        await interaction.deferReply();

        // 2. Check if user is in the same voice channel
        if (player && player.voiceId !== interaction.member.voice.channelId) {
            return interaction.editReply(buildV2Message(`${e.ICON_WARNING} You must be in the same voice channel as the bot.`));
        }

        const query = interaction.options.getString("query");
        
        // 3. Update the deferred message so the user knows the bot is searching
        await interaction.editReply(buildV2Message(`${e.ICON_SEARCH} Searching for \`${query}\``));
        
        // 4. Perform the search
        const searchOptions = { requester: interaction.member };
        if (!query.startsWith('http')) {
            searchOptions.sourceID = client.config.defaultSearchEngine === 'youtubeMusic' ? 'ytm' :
                                 client.config.defaultSearchEngine === 'youtube' ? 'yt' :
                                 client.config.defaultSearchEngine === 'soundcloud' ? 'sc' :
                                 client.config.defaultSearchEngine === 'spotify' ? 'sp' :
                                 'yt'; 
        } else {
            if (query.includes('youtube.com/watch') || query.includes('youtu.be/') ||
                query.includes('music.youtube.com') || query.includes('youtube.com/playlist')) {
                searchOptions.sourceID = 'ytm'; 
            } else if (query.includes('spotify.com')) {
                searchOptions.sourceID = 'sp';
            } else if (query.includes('soundcloud.com')) {
                searchOptions.sourceID = 'sc';
            }
        }

        let result = await client.rainlink.search(query, searchOptions);
        
        // Auto-retry once for Spotify URLs
		if ((result.type === "ERROR" || !result.tracks?.length) && query.includes("spotify.com")) {
		    for (let attempt = 0; attempt < SPOTIFY_RETRY_COUNT; attempt++) {
		        await new Promise(r => setTimeout(r, SPOTIFY_RETRY_DELAY_MS));
		        result = await client.rainlink.search(query, searchOptions);
		        if (result.type !== "ERROR" && result.tracks?.length) break;
		    }
		}

        // 5. Handle empty or errored results
        if (result.type === "EMPTY" || result.type === "ERROR" || !result.tracks.length) {
            const errorMessage = result.exception?.message
                || result.exception?.cause?.message
                || (result.exception?.cause && typeof result.exception.cause === 'object' && result.exception.cause.message)
                || (Array.isArray(result.exception?.errors) && result.exception.errors.map(err => err.message).join(' '))
                || "";

            if (result.type === "ERROR" && errorMessage) {
                console.error(`[PLAY COMMAND] Search error for query "${query}":`, errorMessage);
            }

            if (isSpotifyAutoGeneratedPlaylistError(errorMessage) || isSpotifyAutoGeneratedPlaylistUrl(query)) {
                return interaction.editReply(buildV2Message(
                    `${e.ICON_WARNING} **Spotify auto-generated playlists (Daily Mix, Discover Weekly, Release Radar, radio stations, etc.) sometimes fail to load due to a Spotify-side restriction.**\n\nThe playlist you tried to play couldn't be loaded this time. You can try again — it may work on another attempt — or copy the songs into your own playlist on Spotify first for reliable playback.`
                ));
            }

            if (result.type === "ERROR") {
                return interaction.editReply(buildV2Message(`${e.ICON_ERROR} Search error: ${errorMessage || 'Unknown error occurred during search.'}`));
            } else if (result.type === "EMPTY") {
                return interaction.editReply(buildV2Message(`${e.ICON_ERROR} No results found for your query. The video may be unavailable, restricted, or the search returned no results.`));
            } else if (!result.tracks.length) {
                return interaction.editReply(buildV2Message(`${e.ICON_ERROR} Search completed but no tracks were found. Please TRY AGAIN`));
            } else {
                return interaction.editReply(buildV2Message(`${e.ICON_ERROR} No results found for your query.`));
            }
        }

        // 6. Create the player if one doesn't exist yet
        if (!player) {
            player = await client.rainlink.create({
                guildId: interaction.guildId,
                textId: interaction.channelId,
                voiceId: interaction.member.voice.channelId,
                shardId: interaction.guild.shardId,
                volume: client.config.defaultVolume,
                deaf: true,
            });
            player.playedHistory = new Set();
        }

        const wasIdle = !player.queue.current;

        // 7. Process the search results into the queue
        let finalMessage = "";

        if (result.type === "PLAYLIST") {
            const currentSize = player.queue.size + (player.playing ? 1 : 0);
            const availableSpace = client.config.maxQueueSize - currentSize;
            
            if (availableSpace <= 0) {
                return interaction.editReply(buildV2Message(`${e.ICON_WARNING} Queue is full (max ${client.config.maxQueueSize} tracks). Cannot add playlist.`));
            }
            
            let tracksAdded = 0;
            for (const track of result.tracks) {
                if (currentSize + tracksAdded >= client.config.maxQueueSize) break;
                
                player.queue.add(track);
                queueLoudnessAnalysis(track, (cached, avgGain) => {
                    if (player.queue.current && getCacheKey(player.queue.current) === getCacheKey(track)) {
                        applyGainCorrection(player, player.queue.current, client);
                    }
                });
                tracksAdded++;
            }

            if (tracksAdded === 0) {
                return interaction.editReply(buildV2Message(`${e.ICON_WARNING} Queue is full (max ${client.config.maxQueueSize} tracks). Cannot add any tracks from this playlist.`));
            } else if (tracksAdded < result.tracks.length) {
                finalMessage = `${e.ICON_PLAYLIST} Added **${tracksAdded}** of **${result.tracks.length}** songs from **${result.playlistName}**. Queue limit reached.`;
            } else {
                finalMessage = `${e.ICON_PLAYLIST} Added **${result.playlistName}** - \`${result.tracks.length}\` songs to the queue.`;
            }
        } else {
            // Single track
            const currentSize = player.queue.size + (player.playing ? 1 : 0);
            if (currentSize >= client.config.maxQueueSize) {
                return interaction.editReply(buildV2Message(`${e.ICON_WARNING} Queue is full (max ${client.config.maxQueueSize} tracks). Cannot add this track.`));
            }

            const track = result.tracks[0];
            const trackTitle = formatString(track.title, 30).replace(/ - Topic$/, "") || "Unknown";
            const trackAuthor = formatString(track.author, 25).replace(/ - Topic$/, "") || "Unknown";

            player.queue.add(track);
            queueLoudnessAnalysis(track, (cached, avgGain) => {
                if (player.queue.current && getCacheKey(player.queue.current) === getCacheKey(track)) {
                    applyGainCorrection(player, player.queue.current, client);
                }
            });

            // Clean, non-hyperlinked plain text format!
            finalMessage = `${e.ICON_SUCCESS} Added **${trackTitle} -${trackAuthor}** - \`${convertTime(track.duration)}\``;
        }

        // 8. Show the final success message
        await interaction.editReply(buildV2Message(finalMessage));

        console.log(`[NEWGUI] Pass the edit Reply with final message: ${finalMessage}`);

        // 9. Start the music!
        // if (!player.playing) return player.play();
        if (wasIdle) {
            await player.play();
            console.log(`[NEWGUI] Player was idle, started playback.`);
        }
        console.log(`[NEWGUI] Play command completed for query: ${query}`);
    },
};

function formatString(str, maxLength) {
    return str.length > maxLength ? str.substr(0, maxLength - 3) + "..." : str;
}

// Simple in-memory cache for recent autocomplete queries to reduce latency
// Cache search results for 60 seconds
const __autocompleteCache = new Map(); // key -> { ts, choices }

// Track the latest keystroke per user for debouncing
const __userTypingTracker = new Map(); // userId -> latestFocusedString

// Sleep helper
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// Helper: promise with timeout
function withTimeout(promise, ms) {
    return Promise.race([
        promise,
        new Promise((resolve) => setTimeout(() => resolve(null), ms)),
    ]);
}

// --- SPOTIFY TOKEN MEMORY CACHE ---
let cachedSpotifyToken = null;
let tokenExpiresAt = 0;
let isFetchingToken = false; // Prevents spamming the API with requests

// Background Task: Fetch a new token if expired
async function refreshSpotifyTokenBackground() {
    if (isFetchingToken) return;
    isFetchingToken = true;
    try {
        console.log(`[Spotify] Token missing/expired. Fetching new one in background...`);
        const res = await fetch("http://127.0.0.1:3000/api/token");
        if (res.ok) {
            const data = await res.json();
            if (data.access_token) {
                cachedSpotifyToken = data.access_token;
                tokenExpiresAt = Date.now() + (50 * 60 * 1000); 
                console.log(`[Spotify] Background fetch complete. New token active.`);
            }
        }
    } catch (e) {
        console.log(`[Spotify] Background token fetch failed:`, e.message);
    } finally {
        isFetchingToken = false;
    }
}

// Background Task: Rotate burner account if Spotify API rate-limits us
async function rotateSpotifyTokenBackground() {
    if (isFetchingToken) return;
    isFetchingToken = true;
    try {
        console.log(`[Spotify] 429 Rate Limit Hit! Triggering burner account rotation in background...`);
        const res = await fetch("http://127.0.0.1:3000/api/rotate/token");
        if (res.ok) {
            const data = await res.json();
            if (data.access_token) {
                cachedSpotifyToken = data.access_token;
                tokenExpiresAt = Date.now() + (50 * 60 * 1000);
                console.log(`[Spotify] Rotation successful. Swapped to [${data.account}].`);
            }
        }
    } catch (e) {
        console.log(`[Spotify] Background rotation failed:`, e.message);
    } finally {
        isFetchingToken = false;
    }
}

// Search Spotify Web API directly with non-blocking failovers
async function searchSpotifyDirect(query, limit = 5) {
    if (!cachedSpotifyToken || Date.now() > tokenExpiresAt) {
        refreshSpotifyTokenBackground(); 
        return [];
    }

    try {
        const url = `https://api.spotify.com/v1/search?q=${encodeURIComponent(query)}&type=track&market=TH&limit=10`;
        const res = await fetch(url, {
            headers: { Authorization: `Bearer ${cachedSpotifyToken}` },
        });

        if (!res.ok) {
            if (res.status === 429) {
                cachedSpotifyToken = null;
                rotateSpotifyTokenBackground(); 
            } else if (res.status === 401) {
                cachedSpotifyToken = null;
                refreshSpotifyTokenBackground(); 
            }
            return []; 
        }

        const data = await res.json();
        const tracks = data.tracks?.items || [];

        const uniqueTracks = [];
        const seenKeys = new Set();

        for (const track of tracks) {
            const title = track.name || "Unknown";
            const artist = track.artists?.[0]?.name || "Unknown";
            
            const dedupKey = `${title.toLowerCase()} - ${artist.toLowerCase()}`;
            if (seenKeys.has(dedupKey)) continue;
            seenKeys.add(dedupKey);

            let label = `🟢 ${title} — ${artist}`;
            if (label.length > 100) label = label.substring(0, 97) + "...";

            const value = track.external_urls?.spotify || `${title} - ${artist}`;
            
            uniqueTracks.push({
                name: label,
                value: value.length > 100 ? value.substring(0, 100) : value,
            });

            if (uniqueTracks.length >= limit) break;
        }

        return uniqueTracks;
    } catch (e) {
        return [];
    }
}

// Autocomplete handler for `/play`
module.exports.autocomplete = async (client, interaction) => {
    const handlerStart = Date.now();
    try {
        const focused = interaction.options.getFocused();
        const trimmed = focused ? focused.trim() : "";

        if (trimmed.length < 2) {
            return interaction.respond([]);
        }

        const cacheKey = `play:autocomplete:${trimmed.toLowerCase()}`;
        const cached = __autocompleteCache.get(cacheKey);
        const now = Date.now();
        if (cached && now - cached.ts < 60000) {
            return interaction.respond(cached.choices.slice(0, 10)); 
        }

        const userId = interaction.user.id;
        __userTypingTracker.set(userId, focused);

        await sleep(200);

        if (__userTypingTracker.get(userId) !== focused) {
            return interaction.respond([]); 
        }

        const maxTotalResults = 10;
        const maxSpotifyResults = 5;
        const searchTimeout = 2200; 

        let spotifyChoices = await withTimeout(searchSpotifyDirect(trimmed, maxSpotifyResults), searchTimeout) || [];
        
        let remainingSlots = maxTotalResults - spotifyChoices.length;
        let finalChoices = [...spotifyChoices];

        if (remainingSlots > 0) {
            const ytmSlots = Math.ceil(remainingSlots / 2);
            const ytSlots = Math.floor(remainingSlots / 2);

            const [ytmResults, ytResults] = await Promise.all([
                withTimeout(
                    client.rainlink.search(trimmed, { requester: interaction.user, sourceID: "ytm" }).catch(() => null),
                    searchTimeout
                ),
                withTimeout(
                    client.rainlink.search(trimmed, { requester: interaction.user, sourceID: "yt" }).catch(() => null),
                    searchTimeout
                )
            ]);

            const formatTracks = (res, limit) => {
                if (!res?.tracks || !Array.isArray(res.tracks)) return [];
                return res.tracks.slice(0, limit).map((t) => {
                    const title = (t.title || t.info?.title || "Unknown").toString();
                    const author = (t.author || t.info?.author || "Unknown").toString();
                    let label = `🔴 ${title} — ${author}`;
                    if (label.length > 100) label = label.substring(0, 97) + "...";
                    return {
                        name: label,
                        value: (t.uri || t.info?.uri || `${title} - ${author}`).toString(),
                    };
                });
        	};

	        const ytmChoices = formatTracks(ytmResults, ytmSlots);
	        const ytChoices = formatTracks(ytResults, ytSlots);

            finalChoices = [...finalChoices, ...ytmChoices, ...ytChoices];
        }

        finalChoices = finalChoices.slice(0, 10);

        const totalElapsed = Date.now() - handlerStart;

        try {
            client.utils?.logger?.debug?.(
                `[Autocomplete] responding with ${finalChoices.length} choices in ${totalElapsed}ms for query="${focused}"`
            );
        } catch (e) {}

        __autocompleteCache.set(cacheKey, { ts: now, choices: finalChoices });

        if (__userTypingTracker.get(userId) === focused) {
            __userTypingTracker.delete(userId);
        }

        return interaction.respond(finalChoices);
    } catch (error) {
        try {
            client.utils?.logger?.error?.("Autocomplete error:", error);
        } catch (e) {}
        
        try {
            return interaction.respond([]);
        } catch (e) {}
    }
};